//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfiguratorPCEntities : DbContext
    {
        public ConfiguratorPCEntities()
            : base("name=ConfiguratorPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CaseConnector> CaseConnectors { get; set; }
        public DbSet<CaseSize> CaseSizes { get; set; }
        public DbSet<Chipset> Chipsets { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Component> Components { get; set; }
        public DbSet<Connector> Connectors { get; set; }
        public DbSet<Core> Cores { get; set; }
        public DbSet<GraphicProcessor> GraphicProcessors { get; set; }
        public DbSet<LightingType> LightingTypes { get; set; }
        public DbSet<LiquidCooler> LiquidCoolers { get; set; }
        public DbSet<M2FormFactor> M2FormFactor { get; set; }
        public DbSet<M2Key> M2Key { get; set; }
        public DbSet<M2SSD> M2SSD { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Microarchitecture> Microarchitectures { get; set; }
        public DbSet<MotherBoardConnector> MotherBoardConnectors { get; set; }
        public DbSet<MotherBoardFormFactor> MotherBoardFormFactors { get; set; }
        public DbSet<MotherBoardM2Key> MotherBoardM2Key { get; set; }
        public DbSet<MotherBoardPowerConnector> MotherBoardPowerConnectors { get; set; }
        public DbSet<MotherBoardPowerPlug> MotherBoardPowerPlugs { get; set; }
        public DbSet<NetworkAdapterChipset> NetworkAdapterChipsets { get; set; }
        public DbSet<PCIEController> PCIEControllers { get; set; }
        public DbSet<PowerSupply> PowerSupplies { get; set; }
        public DbSet<PowerSupplyFormFactor> PowerSupplyFormFactors { get; set; }
        public DbSet<PowerSupplyMotherBoardConnector> PowerSupplyMotherBoardConnectors { get; set; }
        public DbSet<PowerSupplyProcessorPowerConnector> PowerSupplyProcessorPowerConnectors { get; set; }
        public DbSet<PowerSupplyVideoPowerConnector> PowerSupplyVideoPowerConnectors { get; set; }
        public DbSet<ProcessorCooler> ProcessorCoolers { get; set; }
        public DbSet<ProcessorPowerConnector> ProcessorPowerConnectors { get; set; }
        public DbSet<ProcessorPowerPlug> ProcessorPowerPlugs { get; set; }
        public DbSet<RAM> RAMs { get; set; }
        public DbSet<RAMFormFactor> RAMFormFactors { get; set; }
        public DbSet<RAMType> RAMTypes { get; set; }
        public DbSet<Socket> Sockets { get; set; }
        public DbSet<SoundAdapterChipset> SoundAdapterChipsets { get; set; }
        public DbSet<VideoCardPowerPlug> VideoCardPowerPlugs { get; set; }
        public DbSet<VideoMemoryType> VideoMemoryTypes { get; set; }
        public DbSet<VideoOutput> VideoOutputs { get; set; }
        public DbSet<VideoPowerConnector> VideoPowerConnectors { get; set; }
        public DbSet<Cooler> Coolers { get; set; }
        public DbSet<DataStorage> DataStorages { get; set; }
        public DbSet<HDD> HDDs { get; set; }
        public DbSet<SSD> SSDs { get; set; }
        public DbSet<GraphicsProcessingUnit> GraphicsProcessingUnits { get; set; }
        public DbSet<Processor> Processors { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<Case> Cases { get; set; }
        public DbSet<RadiatorSize> RadiatorSizes { get; set; }
        public DbSet<VideoCard> VideoCards { get; set; }
        public DbSet<VideoCardOutput> VideoCardOutputs { get; set; }
        public DbSet<MotherBoard> MotherBoards { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Rule> Rules { get; set; }
    }
}
