//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connector
    {
        public Connector()
        {
            this.CaseConnectors = new HashSet<CaseConnector>();
            this.MotherBoardConnectors = new HashSet<MotherBoardConnector>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CaseConnector> CaseConnectors { get; set; }
        public virtual ICollection<MotherBoardConnector> MotherBoardConnectors { get; set; }
    }
}
