//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicsProcessingUnit
    {
        public GraphicsProcessingUnit()
        {
            this.Processors = new HashSet<Processor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short MaxFrequency { get; set; }
        public byte ExecutiveUnitQuantity { get; set; }
        public short ShadingUnitsQuantity { get; set; }
    
        public virtual ICollection<Processor> Processors { get; set; }
    }
}
