//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M2FormFactor
    {
        public M2FormFactor()
        {
            this.M2SSD = new HashSet<M2SSD>();
            this.MotherBoardM2Key = new HashSet<MotherBoardM2Key>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<M2SSD> M2SSD { get; set; }
        public virtual ICollection<MotherBoardM2Key> MotherBoardM2Key { get; set; }
    }
}
