//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.LiquidCoolers = new HashSet<LiquidCooler>();
            this.ProcessorCoolers = new HashSet<ProcessorCooler>();
            this.Coolers = new HashSet<Cooler>();
            this.Cases = new HashSet<Case>();
            this.Cases1 = new HashSet<Case>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<LiquidCooler> LiquidCoolers { get; set; }
        public virtual ICollection<ProcessorCooler> ProcessorCoolers { get; set; }
        public virtual ICollection<Cooler> Coolers { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Case> Cases1 { get; set; }
    }
}
