//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoardPowerConnector
    {
        public MotherBoardPowerConnector()
        {
            this.PowerSupplyMotherBoardConnectors = new HashSet<PowerSupplyMotherBoardConnector>();
            this.MotherBoardPowerPlugs = new HashSet<MotherBoardPowerPlug>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PowerSupplyMotherBoardConnector> PowerSupplyMotherBoardConnectors { get; set; }
        public virtual ICollection<MotherBoardPowerPlug> MotherBoardPowerPlugs { get; set; }
    }
}
