//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSupply
    {
        public PowerSupply()
        {
            this.PowerSupplyMotherBoardConnectors = new HashSet<PowerSupplyMotherBoardConnector>();
            this.PowerSupplyProcessorPowerConnectors = new HashSet<PowerSupplyProcessorPowerConnector>();
            this.PowerSupplyVideoPowerConnectors = new HashSet<PowerSupplyVideoPowerConnector>();
        }
    
        public int IdComponent { get; set; }
        public int IdPowerSupplyFormFactor { get; set; }
        public short Power { get; set; }
        public byte SATAConnectorQuantity { get; set; }
        public int IdColor { get; set; }
        public string CoolerSystem { get; set; }
        public short Length { get; set; }
        public short Width { get; set; }
        public short Heigth { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Component Component { get; set; }
        public virtual PowerSupplyFormFactor PowerSupplyFormFactor { get; set; }
        public virtual ICollection<PowerSupplyMotherBoardConnector> PowerSupplyMotherBoardConnectors { get; set; }
        public virtual ICollection<PowerSupplyProcessorPowerConnector> PowerSupplyProcessorPowerConnectors { get; set; }
        public virtual ICollection<PowerSupplyVideoPowerConnector> PowerSupplyVideoPowerConnectors { get; set; }
    }
}
