//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessorPowerConnector
    {
        public ProcessorPowerConnector()
        {
            this.PowerSupplyProcessorPowerConnectors = new HashSet<PowerSupplyProcessorPowerConnector>();
            this.ProcessorPowerPlugs = new HashSet<ProcessorPowerPlug>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PowerSupplyProcessorPowerConnector> PowerSupplyProcessorPowerConnectors { get; set; }
        public virtual ICollection<ProcessorPowerPlug> ProcessorPowerPlugs { get; set; }
    }
}
