//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessorCooler
    {
        public ProcessorCooler()
        {
            this.Sockets = new HashSet<Socket>();
        }
    
        public int IdComponent { get; set; }
        public int IdRadiatorMaterial { get; set; }
        public byte FanQuantity { get; set; }
        public string FanSize { get; set; }
        public string FanConnector { get; set; }
        public short MaxRotationSpeed { get; set; }
        public short MinRotationSpeed { get; set; }
        public string AdjustmentRotationSpeed { get; set; }
        public Nullable<byte> MaxNoiseLevel { get; set; }
        public Nullable<decimal> MaxAirflow { get; set; }
        public Nullable<decimal> MaxStaticPressure { get; set; }
        public string BearingType { get; set; }
        public short TDP { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual LiquidCooler LiquidCooler { get; set; }
        public virtual Material Material { get; set; }
        public virtual ICollection<Socket> Sockets { get; set; }
        public virtual Cooler Cooler { get; set; }
    }
}
