//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiatorSize
    {
        public RadiatorSize()
        {
            this.LiquidCoolers = new HashSet<LiquidCooler>();
            this.Cases = new HashSet<Case>();
        }
    
        public int Id { get; set; }
        public short Size { get; set; }
    
        public virtual ICollection<LiquidCooler> LiquidCoolers { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
    }
}
