//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int ID { get; set; }
        public Nullable<int> CurrentState { get; set; }
        public Nullable<int> Rj { get; set; }
        public Nullable<int> NextState { get; set; }
        public string Memo { get; set; }
    }
}
