//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCardPowerPlug
    {
        public VideoCardPowerPlug()
        {
            this.VideoPowerConnectors = new HashSet<VideoPowerConnector>();
            this.VideoCards = new HashSet<VideoCard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VideoPowerConnector> VideoPowerConnectors { get; set; }
        public virtual ICollection<VideoCard> VideoCards { get; set; }
    }
}
